# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, null=True)),
                ('countsum', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='poke',
            name='pokeduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked_user', to='login.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='pokeruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_user', to='login.User'),
        ),
    ]
