# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('travel_date_from', models.DateField(max_length=255)),
                ('travel_date_to', models.DateField(max_length=255)),
                ('planned_by', models.ManyToManyField(related_name='users_booked', to='login.Users')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_created', to='login.Users')),
            ],
        ),
    ]
