# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_trip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='Trips',
        ),
    ]
